import type { IndustryId, IndustryTemplate } from "../types/prompt";

export const industryTemplates: Record<IndustryId, IndustryTemplate> = {
  general: {
    id: "general",
    name: "通用电商",
    keywords: ["清晰卖点", "真实使用", "信任证明", "转化引导"],
    suitableProducts: ["各类电商实物产品", "服务型产品", "工具型产品"],
    focus: ["产品核心质感", "真实使用过程", "场景化演示", "明确购买理由"],
    defaultScene: "干净明亮的电商拍摄空间，背景简洁，有适度留白，产品处于视觉中心。",
    defaultLighting: "柔和主光配合轻微侧逆光，画面通透，产品边缘轮廓清晰。",
    defaultPhysicalInteraction: "真实展示产品被拿起、打开、使用、放回的连续物理过程。",
    trustProof: "通过细节特写、真实使用反馈和关键参数展示建立信任。",
    ctaHint: "引导用户点击购买、咨询或收藏，语气自然明确。",
  },
  beauty: {
    id: "beauty",
    name: "美妆行业",
    keywords: ["质感", "显色", "持妆", "妆效", "肤色适配"],
    suitableProducts: ["口红", "粉底液", "眼影", "护肤品"],
    focus: ["微距膏体质感", "上脸效果", "防水测试", "持妆证明", "黄皮显白", "妆效对比"],
    defaultScene: "干净梳妆台和柔和肤色背景，桌面只保留产品、镜子和少量美妆道具。",
    defaultLighting: "柔和大面积美妆灯，肤色自然，膏体和皮肤纹理清晰不油腻。",
    defaultPhysicalInteraction: "展示膏体滑动、粉质晕染、液体延展、上脸服帖和防水摩擦测试。",
    trustProof: "通过上脸前后对比、防水测试和持妆细节证明效果。",
    ctaHint: "突出适配肤色、妆效和当前优惠，引导点击购买。",
  },
  digital: {
    id: "digital",
    name: "数码3C行业",
    keywords: ["科技感", "性能", "品质测试", "参数", "触控体验"],
    suitableProducts: ["手机", "耳机", "小家电", "智能设备"],
    focus: ["金属机身", "屏幕触控", "性能参数", "防摔防水", "配件完整", "科技光感"],
    defaultScene: "现代桌面或科技感生活空间，背景干净，保留线性灯光和少量数码道具。",
    defaultLighting: "冷暖平衡的科技光感，屏幕不过曝，金属边缘有清晰高光。",
    defaultPhysicalInteraction: "展示按键反馈、屏幕触控、开合阻尼、接口插拔和配件连接过程。",
    trustProof: "通过参数字幕、实测画面、抗摔防水或续航展示建立品质信任。",
    ctaHint: "强调配置、体验和入手理由，引导咨询或点击购买。",
  },
  maternal: {
    id: "maternal",
    name: "母婴行业",
    keywords: ["安全", "柔软", "宝宝反馈", "亲肤", "无刺激"],
    suitableProducts: ["奶粉", "纸尿裤", "玩具", "婴儿护肤"],
    focus: ["安全成分", "柔软亲肤", "宝宝真实反应", "吸水测试", "检测报告", "温馨家庭场景"],
    defaultScene: "温馨家庭客厅或婴儿房，背景柔和整洁，母婴用品摆放自然。",
    defaultLighting: "暖色柔光，人物肤色健康，宝宝与产品细节清晰舒适。",
    defaultPhysicalInteraction: "展示触摸、拉扯、吸水、涂抹、抓握等温和真实的产品互动。",
    trustProof: "通过成分、安全检测、宝宝反馈和实测对比建立信任。",
    ctaHint: "用安心、亲肤、适合宝宝的理由引导咨询或购买。",
  },
  food: {
    id: "food",
    name: "食品行业",
    keywords: ["食欲", "新鲜", "ASMR", "口感", "热气", "拉丝", "汁水"],
    suitableProducts: ["火锅", "零食", "饮品", "烘焙", "生鲜"],
    focus: ["汤汁挂壁", "拉丝", "酥脆纹理", "热气", "新鲜食材", "咀嚼声", "包装完整"],
    defaultScene: "干净餐桌或厨房台面，食材和包装摆放整洁，画面有食欲但不杂乱。",
    defaultLighting: "暖色食物摄影光，突出热气、油亮、汁水和新鲜纹理。",
    defaultPhysicalInteraction: "展示开袋、倒出、夹起、撕开、拉丝、咀嚼或饮用的真实过程。",
    trustProof: "通过新鲜食材、口感细节、包装信息和真实试吃反馈建立信任。",
    ctaHint: "突出口感、规格和购买理由，引导下单或囤货。",
  },
  fashion: {
    id: "fashion",
    name: "服饰行业",
    keywords: ["面料质感", "上身效果", "版型", "显瘦", "垂坠感"],
    suitableProducts: ["连衣裙", "裤子", "上衣", "鞋包"],
    focus: ["面料纤维", "垂坠感", "走动展示", "显瘦版型", "拉扯测试", "全身穿搭"],
    defaultScene: "简洁试衣间、街拍空间或居家穿搭场景，背景干净，人物全身轮廓清楚。",
    defaultLighting: "自然柔光，布料纹理和版型阴影清晰，肤色和衣物颜色不偏色。",
    defaultPhysicalInteraction: "展示面料揉捏、拉扯、转身、走动和不同角度上身效果。",
    trustProof: "通过版型对比、面料细节、走动垂坠和身材修饰效果建立信任。",
    ctaHint: "突出显瘦、百搭和适用场合，引导点击购买。",
  },
  knowledge: {
    id: "knowledge",
    name: "知识付费行业",
    keywords: ["痛点共鸣", "干货密度", "权威背书", "学习成果", "限时名额"],
    suitableProducts: ["课程", "书籍", "培训", "工具"],
    focus: ["痛点场景", "课程大纲", "工具演示", "学员反馈", "权威证明", "限时优惠"],
    defaultScene: "干净书桌、办公室或线上课程界面，画面有笔记、电脑和清晰课程资料。",
    defaultLighting: "清爽自然的办公光线，屏幕内容清晰，人物面部可信专业。",
    defaultPhysicalInteraction: "展示翻书、写笔记、点击课程、演示工具和查看学习成果。",
    trustProof: "通过课程大纲、案例反馈、权威证明和成果前后对比建立信任。",
    ctaHint: "强调学习成果、适合人群和咨询入口，引导报名或私信。",
  },
};

export const getIndustryTemplate = (industry: IndustryId): IndustryTemplate =>
  industryTemplates[industry] ?? industryTemplates.general;

export const industryOptions = Object.values(industryTemplates);
